/* ============================================================
   ViZion — Annuaire des contacts hôtels
   Personnes de contact connues par hôtel (nom, fonction,
   téléphone, email), utilisé pour pré-remplir la liste des
   personnes présentes une fois l'hôtel sélectionné
   (pages/buildings.html). L'utilisateur peut ensuite ajouter,
   modifier ou retirer des personnes librement.
============================================================ */

window.HOTEL_CONTACTS = [
    { nom: "Ocloo", prenom: "Justine", fonction: "Responsable qse", email: "j-ocloo@palm.re", telFixe: "0262 56 30 30", telPortable: "+33", hotels: ["Palm", "Iloha"] },
    { nom: "Peta", prenom: "Patrice", fonction: "Directeur général", email: "patrice.peta@palm.re", telFixe: "", telPortable: "", hotels: ["Palm"] },
    { nom: "Nicolas", prenom: "Nathalie", fonction: "Responsable communication", email: "marketing@hotels-co.fr", telFixe: "", telPortable: "0688416333", hotels: ["Palm", "Iloha"] },
    { nom: "Peta", prenom: "David", fonction: "Directeur général", email: "david.peta@iloha.fr", telFixe: "", telPortable: "", hotels: ["Iloha"] },
    { nom: "Teiti", prenom: "Arnaud", fonction: "Directeur exploitation", email: "arnaud@oussa-nou-dor.net", telFixe: "", telPortable: "+262 693558533", hotels: ["Le Grand Bleu", "Les Aigrettes", "Tama Hôtel"] },
    { nom: "Boulo", prenom: "Guy", fonction: "Directeur général", email: "guy@oussa-nou-dor.com", telFixe: "", telPortable: "+262", hotels: ["Le Grand Bleu", "Les Aigrettes", "Tama Hôtel"] },
    { nom: "Direction", prenom: "", fonction: "", email: "direction@tama-hotel.com", telFixe: "", telPortable: "", hotels: ["Tama Hôtel"] },
    { nom: "Réception", prenom: "", fonction: "", email: "reservation@tama-hotel.com", telFixe: "", telPortable: "", hotels: ["Tama Hôtel"] },
    { nom: "Dijoux", prenom: "Jean", fonction: "Dirigeant", email: "direction@villadelisle.re", telFixe: "", telPortable: "", hotels: ["Villa Delisle"] },
    { nom: "Moulin-tanguy", prenom: "Marie-pierre", fonction: "", email: "Reservation@relais-hermitage-saintgilles.fr", telFixe: "+262 244444", telPortable: "", hotels: ["Relais de l'Hermitage"] },
    { nom: "Naguin coupin", prenom: "Claudette", fonction: "Directrice générale", email: "claudette.nc@relais-hermitage-saintgilles.fr", telFixe: "+262 0262334105", telPortable: "+262 0692863337", hotels: ["Relais de l'Hermitage"] },
    { nom: "Lefumat", prenom: "Audrey", fonction: "Chargée de communication", email: "", telFixe: "+262 334112", telPortable: "+262", hotels: ["Relais de l'Hermitage"] },
    { nom: "Wolff", prenom: "Christian", fonction: "Gérant", email: "christian.wolff@cotesunhotels.com", telFixe: "06 92 66 78 17", telPortable: "", hotels: ["Le Saint-Pierre", "Wood Hôtel & SPA"] },
    { nom: "Clemenard", prenom: "Elodie", fonction: "Directrice d'exploitation", email: "direction@hotellesaintpierre.fr", telFixe: "+262 0262611611", telPortable: "", hotels: ["Le Saint-Pierre"] },
    { nom: "Fillon", prenom: "Cécile", fonction: "(ex) responsable rse", email: "", telFixe: "", telPortable: "", hotels: ["Floralys", "Victoria", "Roseaux des Sables", "Créolia", "Alamanda"] },
    { nom: "Mondésir", prenom: "Brigitte", fonction: "Directrice d'exploitation", email: "direction@floralys.re", telFixe: "0262 91 79 79", telPortable: "0692 14 73 00", hotels: ["Floralys", "Roseaux des Sables"] },
    { nom: "Lefebvre", prenom: "Yann", fonction: "Propriétaire - gérant", email: "", telFixe: "", telPortable: "", hotels: ["Floralys", "Roseaux des Sables"] },
    { nom: "Gibey", prenom: "Ilona", fonction: "Directrice d'exploitation", email: "direction@levictoria.re", telFixe: "", telPortable: "0692 504 180", hotels: ["Victoria"] },
    { nom: "Turonnet", prenom: "Pascal", fonction: "Directeur général", email: "direction.creolia@exsel.re", telFixe: "0262 94 26 25", telPortable: "06 92 69 48 34", hotels: ["Créolia"] },
    { nom: "M. rosay", prenom: "", fonction: "Responsble technique du groupe exsel", email: "f.rosay@exsel.re", telFixe: "", telPortable: "", hotels: ["Créolia"] },
    { nom: "Bergon", prenom: "Jérémie", fonction: "Directeur adjoint", email: "dir.adjoint-creolia@exsel.re", telFixe: "", telPortable: "", hotels: ["Créolia"] },
    { nom: "Grandsire", prenom: "Vincent", fonction: "", email: "direction@alamanda.re", telFixe: "", telPortable: "", hotels: ["Alamanda"] },
    { nom: "Lucena", prenom: "Adeline", fonction: "Directrice", email: "direction@alamanda.re", telFixe: "0262 33 10 10", telPortable: "0692 44 15 02", hotels: ["Alamanda"] },
    { nom: "Serveaux", prenom: "Béatrice", fonction: "Gérante", email: "Info@lekerveguen.com", telFixe: "", telPortable: "", hotels: ["Le Kervéguen"] },
    { nom: "Vergoz", prenom: "Henri", fonction: "Propriétaire", email: "h.vergoz@hva.re", telFixe: "+262 0262317189", telPortable: "", hotels: ["Le Vieux Cep", "Hôtel Les Géraniums"] },
    { nom: "Vergoz", prenom: "Renée", fonction: "", email: "", telFixe: "", telPortable: "", hotels: ["Le Vieux Cep", "Hôtel Les Géraniums"] },
    { nom: "Morel", prenom: "Clarisse", fonction: "Directrice d'exploitation", email: "c.morel@levieuxcep.re", telFixe: "+33", telPortable: "+262 692695955", hotels: ["Le Vieux Cep"] },
    { nom: "Coquelin", prenom: "Théo", fonction: "(ex) responsable technique groupe macé", email: "", telFixe: "+33", telPortable: "", hotels: ["Les Créoles", "Boucan Canot"] },
    { nom: "Payet", prenom: "Sandrine", fonction: "Directrice du pôle hôtelier groupe macé", email: "direction@boucancanot.com", telFixe: "02 62 33 44 45", telPortable: "", hotels: ["Les Créoles", "Boucan Canot"] },
    { nom: "Leandri", prenom: "Francesca", fonction: "Directrice hébergement", email: "direction@boucancanot.com", telFixe: "02 62 33 44 45", telPortable: "", hotels: ["Les Créoles", "Boucan Canot"] },
    { nom: "Maisonobe", prenom: "Arnaud", fonction: "", email: "", telFixe: "", telPortable: "", hotels: ["Les Créoles"] },
    { nom: "Neveux", prenom: "Stéphanie", fonction: "Directrice d'exploitation", email: "direction@hotellescreoles.com", telFixe: "+33 262265265", telPortable: "", hotels: ["Les Créoles"] },
    { nom: "Maisonobe", prenom: "Arnaud", fonction: "", email: "", telFixe: "", telPortable: "", hotels: ["Boucan Canot"] },
    { nom: "Balaya", prenom: "Caroline", fonction: "", email: "contactlindseyhotel@gmail.com", telFixe: "", telPortable: "06 92 22 10 98", hotels: ["Lindsey Hôtel"] },
    { nom: "Tarona", prenom: "Caroline", fonction: "Gérante", email: "direction@lindsey-hotel-reunion.re", telFixe: "", telPortable: "06 92 22 10 98", hotels: ["Lindsey Hôtel"] },
    { nom: "Douanier", prenom: "Laika", fonction: "Responsable", email: "", telFixe: "+33", telPortable: "+33", hotels: ["Lindsey Hôtel"] },
    { nom: "Pink", prenom: "Yasmine", fonction: "Responsable", email: "", telFixe: "+33", telPortable: "+33", hotels: ["Lindsey Hôtel"] },
    { nom: "Clain", prenom: "Patrice", fonction: "Gérant", email: "patrice@hotel-des-neiges.com", telFixe: "0262317233", telPortable: "", hotels: ["Hôtel des Neiges"] },
    { nom: "Réception", prenom: "", fonction: "", email: "", telFixe: "+262 317233", telPortable: "+33", hotels: ["Hôtel des Neiges"] },
    { nom: "Bordier", prenom: "Jean-paul", fonction: "Propriétaire/gestionnaire", email: "", telFixe: "", telPortable: "", hotels: ["Juliette Dodu"] },
    { nom: "Renie", prenom: "Catherine", fonction: "Propriétaire associé", email: "", telFixe: "", telPortable: "", hotels: ["Juliette Dodu", "Le Nautile"] },
    { nom: "Thomas", prenom: "Doris", fonction: "Directrice financière", email: "dirfi@nautile.re", telFixe: "0262 33 88 88", telPortable: "0692 25 98 56", hotels: ["Juliette Dodu", "Le Nautile"] },
    { nom: "Bordier", prenom: "Jean paul", fonction: "Propriétaire - gérant", email: "", telFixe: "", telPortable: "", hotels: ["Le Nautile"] },
    { nom: "Receptionniste", prenom: "", fonction: "Receptionniste", email: "hotel@nautile.re", telFixe: "0262338888", telPortable: "", hotels: ["Le Nautile"] },
    { nom: "Coriat", prenom: "Dorothée", fonction: "Directrice commerciale", email: "commercial@nautile.re", telFixe: "", telPortable: "", hotels: ["Le Nautile"] },
    { nom: "Domitille", prenom: "Vanille", fonction: "Assist. direction", email: "v.domitile@lesgeraniums.re", telFixe: "", telPortable: "+33 692676598", hotels: ["Hôtel Les Géraniums"] },
    { nom: "Réception", prenom: "", fonction: "", email: "contact@lesgeraniums.re", telFixe: "+33 0262591106", telPortable: "+33", hotels: ["Hôtel Les Géraniums"] },
    { nom: "Del pino", prenom: "Olivia", fonction: "(ex) responsable d'exploitation", email: "olivia.delpino@woodhotel.re", telFixe: "+33", telPortable: "+33", hotels: ["Wood Hôtel & SPA"] },
    { nom: "Texereau", prenom: "Capucine", fonction: "Responsable rse", email: "capucine.texereau@woodhotel.re", telFixe: "+262 0263003030", telPortable: "+262 0693636687", hotels: ["Wood Hôtel & SPA"] },
    { nom: "Zielinski", prenom: "Claudine", fonction: "Responsable d'exploitation", email: "responsable@closdelariviere.re", telFixe: "", telPortable: "+262 693007648", hotels: ["Clos de la Rivière"] },
    { nom: "Wolf", prenom: "Christian", fonction: "Dirigeant", email: "christian.wolff@cotesunhotels.com", telFixe: "+33", telPortable: "+262 692667817", hotels: ["Clos de la Rivière"] }
];
